### ISSUE TITLE
Design HTML layouts for email confirmation

### ISSUE THREAD

**Issue by xation** [xation/PHP-Class-Team-Project#4]
* Stating name of company.
* Thanking customer for order.
* Stating what was ordered.
* How much was ordered.
* Price of each item.
* Total cost of order

**Comment by deadh34d** [comment]
I've been thinking about this. The structure looks good, but we need to decide *when* to send emails also. I think we should send one when a user makes an account, a receipt when they make a purchase, and a third one to let them know when an item that they purchased has shipped.
